version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VARIANT=bullseye
      - VERSION=3.12
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaegertracing:4317
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  
  jaegertracing:
    image: jaegertracing/all-in-one:1.60
    container_name: jaegertracing
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"